title: build(); Hackathon & Incubator
url: https://build.tech.gov.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#490b38"
  secondary-color: "#ea7300"
  media-colors:
    - title: media-color-one
      color: "#ffc187"
    - title: media-color-two
      color: "#ffe1d5"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: build(); is a GovTech-wide Hackathon and Incubator (supported by
  DIP) that aims to empower GovTechies to build the next generation of GovTech
  products for public good!
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.dei9s3quqb02n.amplifyapp.com
prod: https://master.d3ctsdzgfmp6my.amplifyapp.com
facebook-pixel: ""
shareicon: /images/Logo__for_dark_bg____With_desc.png
is_government: true
google_analytics_ga4: ""
linkedin-insights: ""
